server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SkillSwap
    username: postgres
    password: 2898111
    driver-class-name: org.postgresql.Driver

  web:
    resources:
      static-locations: classpath:/static/

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      hibernate.enable_lazy_load_no_trans: true

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.web.servlet: DEBUG
    org.hibernate: DEBUG
    com.example.SkillSwap: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
